repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: flake8
        types: [file, python]
        args:
          - --max-line-length=100

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [file, python]
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        types: [file, python]
        args:
          - --line-length=100

default_language_version:
  python: python3.9
