version: '3'

services:
  postgres:
    image: postgres:14.3
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${NEWS_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${NEWS_DB_USER}
      POSTGRES_PASSWORD: ${NEWS_DB_PASSWORD}
      POSTGRES_DB: ${NEWS_DB_NAME}

volumes:
  database-data:
