"""Add created at field for News model, add index

Revision ID: 519a0e4abb50
Revises: 66042855e652
Create Date: 2022-10-10 12:16:53.021671

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = "519a0e4abb50"
down_revision = "66042855e652"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.create_index(op.f("ix_news_original_link"), "news", ["original_link"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_original_link"), table_name="news")
    op.drop_column("news", "created_at")
    # ### end Alembic commands ###
