"""model Theme field <name> Unique -> True

Revision ID: 66042855e652
Revises: f435c6e54cad
Create Date: 2022-08-19 02:05:15.119325

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "66042855e652"
down_revision = "f435c6e54cad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "theme", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "theme", type_="unique")
    # ### end Alembic commands ###
