"""Make original_link unique, add created_at

Revision ID: 78f88cb82978
Revises: 66042855e652
Create Date: 2022-10-11 15:31:04.537145

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = "78f88cb82978"
down_revision = "66042855e652"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.alter_column("news", "original_link", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.create_unique_constraint(None, "news", ["original_link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "news", type_="unique")
    op.alter_column("news", "original_link", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("news", "created_at")
    # ### end Alembic commands ###
