"""Increase originl_link length

Revision ID: c593eaa82e4b
Revises: 78f88cb82978
Create Date: 2022-10-13 15:11:14.354966

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c593eaa82e4b"
down_revision = "78f88cb82978"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "original_link",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "original_link",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
